services:
  - type: web
    name: flatmate-fight-backend
    runtime: java
    plan: free
    buildCommand: mvn clean install
    startCommand: mvn spring-boot:run
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://YOUR_RENDER_DB_URL:3306/flatmate_db
      - key: SPRING_DATASOURCE_USERNAME
        value: YOUR_DB_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        value: YOUR_DB_PASSWORD
